### ISSUE TITLE
Fortran compiler

### ISSUE THREAD

**Issue by giacomov** [conda-forge/toolchain-feedstock#27] opened 2017-09-22 19:19 UTC
Hi,
I've been looking around for info on how to build a package for conda-forge which needs `gfortran` (or other fortran compiler).

Shouldn't `toolchain` provide one? If not, where should I get it from?

I can make a `gfortran` package myself built with this `toolchain`, but before doing that, I was wondering why `gfortran` is not part of `toolchain`.

**Comment by rmax** [comment] 2017-09-22 19:38
See this recipe as an example: https://github.com/conda-forge/wcslib-feedstock/tree/master/recipe

**Comment by msarahan** [comment] 2017-09-22 19:54
Continuum/Anaconda have new compilers.  These will be available with the
Anaconda 5 release, slated for Monday.  You can get the packages on the
c3i_test2 channel.  For examples of how to use them, see
https://github.com/anacondarecipes/scipy-feedstock

Note that any of the recipes on anacondarecipes will probably require
conda-build 3 to work properly.

**Comment by giacomov** [comment] 2017-09-22 19:57
Does this mean that I shouldn't use `toolchain` anymore for conda-forge packages, starting Monday?

**Comment by msarahan** [comment] 2017-09-22 20:05
That's up to you.  We're providing tools, but which tools you use is totally your choice.  Conda-forge as a whole needs to make a decision, though, as different people in the organization should all use the same set of tools.

Using the same tools as Continuum/Anaconda will confer binary compatibility in a way that we haven't had yet, and that would be very nice.

**Comment by jakirkham** [comment] 2017-09-22 20:07
So I think you are confusing to different things @giacomov. Going to try to briefly clarify things.

First thing is what settings one uses to build packages in conda-forge. This is what the `toolchain` does. It sets things like where to search for headers, libraries, SDK on macOS, etc..

Second thing is what compilers one wants to use. We provide stock compilers on all workers. However if you want something extra, you need to require `gcc` (e.g. for `gfortran`), `clangdev`, or whatever in your recipe's `requirements/build`.

In either case, one still should require the `toolchain` for the build. Other compilers are optional things one can also add in as well.

Going to close this as unrelated, though feel free to ask questions if more occur to you.

**Closed by jakirkham** 2017-09-22 20:07 UTC

**Comment by jakirkham** [comment] 2017-09-22 20:10
Would be great to discuss new compiler tools that Continuum is working on as well, @msarahan. Though this is a relatively low visibility place to do so. Would recommend opening an issue on the webpage and laying out some information to get the discussion started. Thanks in advance both for all of the work put into these new tools and spreading the word. 😄

**Comment by giacomov** [comment] 2017-09-22 20:13
Thanks @jakirkham , that explains a lot of things.

I'd say `toolchain` is then a quite misleading name, if you ask me. In other contexts (for example, the universal binary system used to build python wheels) it means a set of compilers and libraries that everybody uses to build things. That's why I was confused...

Regarding the issue @msarahan is raising, my personal opinion is that conda-forge packages would be better up using the same compilers (I would have said "toolchain" before today ;-) ) that the main Conda system is using, because people are very likely to have packages from both conda-forge and the main Conda channels on their machines. Of course, just my two cents.

**Comment by jakirkham** [comment] 2017-09-22 20:33
As the `toolchain` is quite old and lots of things depend on it, renaming it would be non-trivial at this point. Maybe we can add something to the org docs to help clarify it. What do you think?

Just as FYI we have been using devtoolset-2 (gcc 4.8.2) on Linux and XCode 6.4 (very roughly LLVM 3.6.0) on macOS. At some point we will want newer compiler features (a few people do already), so migrating to something newer is going to happen at some point. Though some coordination and different cases will need working through. All of this is just lead in to that larger discussion.

**Comment by giacomov** [comment] 2017-09-22 20:35
Probably just a few lines in the README.md here on this repository would suffice.

I agree that it is probably way too late to change name.

Thanks for your answers,

**Comment by notestaff** [comment] 2017-10-11 03:52
It's useful to be able to build/test recipes locally.  When toolchain does not include the actual compilers, local conda-build ends up using whatever is installed locally, rather than tools available as conda-forge packages.  That makes local builds not representative of ones on conda-forge.

**Comment by giacomov** [comment] 2017-10-11 05:49
For that, I use the docker container that conda-forge uses, so that the compilers are the same.

 it's a partial solution though, as Mac builds cannot be tested this way.

Sent from my Windows 10 phone

**Comment by jakirkham** [comment] 2017-10-11 12:42
On macOS, we use Xcode 6.4 and make use of the 10.9 SDK included. We also build on macOS 10.10.

**Comment by msarahan** [comment] 2017-10-12 13:13
Including actual compilers was one of the main reasons for developing our compiler packages at Anaconda.  Using those packages decouples the host system from the compilers pretty much completely, making reproducibility of build environment much easier.  Even with those packages, there are caveats due to licensing:

* You still need the MacOS 10.9 SDK
* We can't provide MS compilers as packages (yet?)

I think the most productive use of any debate here is to follow up on the issue at https://github.com/conda-forge/conda-forge.github.io/issues/460 and continue to figure out how to take advantage of the effort that has gone into Anaconda's compiler packages.
